name: build

# Вимкнено автоматичний запуск. Тепер збірка запускається тільки вручну!
on:
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Захист від попереджень GitHub на 2026 рік

jobs:
  msys2-mingw64:
    name: "MSYS2-MinGW (64-bit) - Only ZIP"
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Кешування завантажених пакетів MSYS2
      - name: Cache MSYS2 packages
        uses: actions/cache@v4
        with:
          path: C:\msys64\var\cache\pacman\pkg
          key: msys2-pkgs-${{ hashFiles('**/build.yml') }}

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-cmake mingw-w64-x86_64-autotools mingw-w64-x86_64-tcl git zip

      - name: Build
        run: |
          cd ./Windows
          ./Start.sh
          cmake --build . -j
          cd -
          strip -s ./bin/multicraft.exe

      - name: Create ZIP
        run: |
          mkdir MultiCraft
          cp -r ./bin MultiCraft/
          cp -r ./builtin MultiCraft/
          cp -r ./client MultiCraft/
          cp -r ./fonts MultiCraft/
          cp -r ./locale MultiCraft/
          cp -r ./textures MultiCraft/
          zip -r MultiCraft.zip MultiCraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MultiCraft-msys2-mingw64
          path: ./MultiCraft.zip
